# Основные настройки
title: "Мой сайт"        # Заголовок сайта
description: "Персональная страница"  # Описание
baseurl: ""              # Оставьте пустым для username.github.io
url: "https://maximkinn6.github.io"  # Ваш URL

# Настройки Jekyll
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# Обработка Markdown
markdown: kramdown       # Движок для MD
kramdown:
  input: GFM             # Поддержка GitHub Flavored Markdown
  syntax_highlighter: rouge  # Подсветка кода
